- hosts:
    - all
    - localhost
  gather_facts: true
  roles:
    - role: python
      tags: python
    - role: openssh
      tags: openssh
    - role: brew
      tags: brew
    - role: spotify
      tags: spotify
    - role: jetbrains
      tags: jetbrains
    - role: kubelogin
      tags: kubelogin
    - role: kubectl
      tags: kubectl
    - role: k9s
      tags: k9s
    - role: java
      tags: java
    - role: kind
      tags: kind
